### ISSUE TITLE
Python2 Support

### ISSUE THREAD

**Issue by japroc** [Bashfuscator/Bashfuscator#13]
Hello!

Do you plan python 2 support? 
Currently i found `221 matches across 35 files` with regex `f\"[^\"]*\"` (it searches f-strings supported only in python3). Probably there are some other incompetible things.

**Comment by capnspacehook** [comment]
Hello @japroc, sadly no, I don't plan on Python 2 support. I thought about this for a bit before starting Bashfuscator, and was given some advice that Python 2 was going to be deprecated soon, and if I wanted my Bashfuscator to last, I might as well write it in the future of Python. So you're welcome to create a fork that adds python2 support, shouldn't be too terribly hard if you really want it, but I have no plans of supporting Python 2 at the moment. 

The biggest challenge/annoyance with porting to Python 2 would probably be changing all the Python 3 f-strings to use format(). Other than that it should be relatively easy I think, though i could be wrong. Is there any reason you'd like Python 2 support? Integration with a Python 2 tool maybe?

**Comment by japroc** [comment]
I am thinking about writing some python2-3 compatible tool.
Okay, thank you! If i finally decide to support py2 i will fork and then probably pull request.
