### ISSUE TITLE
First run issue

### ISSUE THREAD

**Issue by Ug0Security** [Bashfuscator/Bashfuscator#14]
Hello,
After install i've encounter an issue for running the program

Traceback (most recent call last):
  File "./bashfuscator", line 293, in <module>
    checkArguments(args)
  File "./bashfuscator", line 170, in checkArguments
    if args.misleading_commands_range:
AttributeError: 'Namespace' object has no attribute 'misleading_commands_range'

After some diggin it seems linked to those commented line 

       #advancedOpts.add_argument("--no-misleading-commands", action="store_false", help="Don't randomly insert misleading commands that do nothing")

    #advancedOpts.add_argument("--misleading-commands-range", type=str, metavar="NUM,NUM", help="The range of random misleading commands to add")

    #advancedOpts.add_argument("--no-integer-expansion", action="store_false", help="Don't expand integers into arithmetic expressions")

    #advancedOpts.add_argument("--integer-expansion-depth", type=check_positive, help="Number of times to recursively expand integers into arithmetic expansions")`

If you uncommented them in /Bashfuscator/bin/bashfuscator it works fine

**Comment by matsest** [comment]
Yes, seems like reverting the last commit should make it work.

**Comment by thisguy23** [comment]
last commit was 25 days ago, issue still exists.

**Comment by capnspacehook** [comment]
Thanks for bringing this to my attention @Ug0Security, I'm really sorry I let this slip into master. It was just one of those "oh let's quick change this tiny thing, can't possibly break anything" moments. I thought I tested it, but guess I didn't. Oh well, latest commit should fix it. Let me know if you find any other issues with Bashfuscator!
