### ISSUE TITLE
Went through install, command not found

### ISSUE THREAD

**Issue by murpsec** [Bashfuscator/Bashfuscator#20]
Ran through install instructions and kicked of the setup.py on a kali box.  Have dependencies but it didn't recognize the bashfuscator command. 

Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3 is already the newest version (3.7.2-1).
python3-argcomplete is already the newest version (1.8.1-1).
python3-pip is already the newest version (18.1-5).
xclip is already the newest version (0.13-1).
0 upgraded, 0 newly installed, 0 to remove and 1880 not upgraded.

root@kali:~/Documents/Bashfuscator# bashfuscator -c "cat /etc/passwd"
bash: bashfuscator: command not found

**Comment by murpsec** [comment]
I added the path manually and fixed, but just wanted to let you know.

**Comment by capnspacehook** [comment]
Yeah that's a known Python thing, that path isn't added by default, but I should probably document that.

Thanks for the heads up!

**Comment by princepeal** [comment]
Hi 

I am facing same issue. 

bashfuscator: command not found

Any solution. 

Thank you

**Comment by capnspacehook** [comment]
Try adding `/home/YOUR_USER/.local/bin` to your PATH, that should fix the issue.

**Comment by BlackKD** [comment]
actually ... I find in this PATH  ~/Bashfuscator/bashfuscator/bin
