### ISSUE TITLE
Create a similar project for powershell obfuscation?

### ISSUE THREAD

**Issue by dmknght** [Bashfuscator/Bashfuscator#23]
Sorry for this off-topic issue. I searched for your email or contact channel but i couldn't see it. I really really love your project. I packaged it and it should be on Parrot Security OS repo soon.
So I am searching a project like this for powershell obfuscation and i am not very happy with the result. I saw powershell projects (If i want to run it on Linux, i have to install extra package) or very limited features projects. I think a cross-platform project (or at least can run on Linux), generate dynamic obfuscated from input everytime, completely change code structure is the best way to bypass AV / IDS / EDR like Bashfuscator is needed for pentesting. So please tell me if you are planing / going to do it.

**Comment by capnspacehook** [comment]
Hey thanks for the kind words and the work for packaging Bashfuscator for Parrot OS!

I am not planning on creating a powershell obfuscation framework for a couple of reasons. One, Daniel Bohannon already has an amazing framework, https://github.com/danielbohannon/Invoke-Obfuscation, which it sounds like you played with a bit. Secondly, powershell tradecraft is pretty much dead, with all the logging available for it and AMSI, writing tradecraft in powershell just isn't worth it nowadays in my opinion. My advice would be to start using some of the great C# tradecraft available, or write your own in C# or a compiled language 😉

**Comment by dmknght** [comment]
Hm I just think it is great if we have a similar project that aims Windows platform. Thanks for your idea i'll find projects like you said :D
